/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlidesCameraRouteImport } from './routes/slides-camera'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MosaicosGdocsPresentationRouteImport } from './routes/mosaicos.gdocs-presentation'
import { Route as MosaicosEditorRouteImport } from './routes/mosaicos.editor'

const SlidesCameraRoute = SlidesCameraRouteImport.update({
  id: '/slides-camera',
  path: '/slides-camera',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MosaicosGdocsPresentationRoute =
  MosaicosGdocsPresentationRouteImport.update({
    id: '/mosaicos/gdocs-presentation',
    path: '/mosaicos/gdocs-presentation',
    getParentRoute: () => rootRouteImport,
  } as any)
const MosaicosEditorRoute = MosaicosEditorRouteImport.update({
  id: '/mosaicos/editor',
  path: '/mosaicos/editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/slides-camera': typeof SlidesCameraRoute
  '/mosaicos/editor': typeof MosaicosEditorRoute
  '/mosaicos/gdocs-presentation': typeof MosaicosGdocsPresentationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/slides-camera': typeof SlidesCameraRoute
  '/mosaicos/editor': typeof MosaicosEditorRoute
  '/mosaicos/gdocs-presentation': typeof MosaicosGdocsPresentationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/slides-camera': typeof SlidesCameraRoute
  '/mosaicos/editor': typeof MosaicosEditorRoute
  '/mosaicos/gdocs-presentation': typeof MosaicosGdocsPresentationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/slides-camera'
    | '/mosaicos/editor'
    | '/mosaicos/gdocs-presentation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/slides-camera'
    | '/mosaicos/editor'
    | '/mosaicos/gdocs-presentation'
  id:
    | '__root__'
    | '/'
    | '/slides-camera'
    | '/mosaicos/editor'
    | '/mosaicos/gdocs-presentation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlidesCameraRoute: typeof SlidesCameraRoute
  MosaicosEditorRoute: typeof MosaicosEditorRoute
  MosaicosGdocsPresentationRoute: typeof MosaicosGdocsPresentationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slides-camera': {
      id: '/slides-camera'
      path: '/slides-camera'
      fullPath: '/slides-camera'
      preLoaderRoute: typeof SlidesCameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosaicos/gdocs-presentation': {
      id: '/mosaicos/gdocs-presentation'
      path: '/mosaicos/gdocs-presentation'
      fullPath: '/mosaicos/gdocs-presentation'
      preLoaderRoute: typeof MosaicosGdocsPresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mosaicos/editor': {
      id: '/mosaicos/editor'
      path: '/mosaicos/editor'
      fullPath: '/mosaicos/editor'
      preLoaderRoute: typeof MosaicosEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlidesCameraRoute: SlidesCameraRoute,
  MosaicosEditorRoute: MosaicosEditorRoute,
  MosaicosGdocsPresentationRoute: MosaicosGdocsPresentationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
